package flc.model;

import java.util.ArrayList;
import java.util.List;

/**
 * Represents a single group exercise lesson at FLC.
 * Each lesson has a fixed capacity of 4 members.
 */
public class Lesson {
    public static final int MAX_CAPACITY = 4;

    private final String lessonId;
    private final Exercise exercise;
    private final Day day;
    private final TimeSlot timeSlot;
    private final int weekendNumber;   // 1–8
    private final List<Booking> bookings;
    private final List<Review> reviews;

    public Lesson(String lessonId, Exercise exercise, Day day, TimeSlot timeSlot, int weekendNumber) {
        this.lessonId = lessonId;
        this.exercise = exercise;
        this.day = day;
        this.timeSlot = timeSlot;
        this.weekendNumber = weekendNumber;
        this.bookings = new ArrayList<>();
        this.reviews = new ArrayList<>();
    }

    // ── Getters ──────────────────────────────────────────────────────────────

    public String getLessonId()      { return lessonId; }
    public Exercise getExercise()    { return exercise; }
    public Day getDay()              { return day; }
    public TimeSlot getTimeSlot()    { return timeSlot; }
    public int getWeekendNumber()    { return weekendNumber; }
    public double getPrice()         { return exercise.getPrice(); }
    public List<Booking> getBookings() { return new ArrayList<>(bookings); }
    public List<Review> getReviews() { return new ArrayList<>(reviews); }

    // ── Capacity helpers ─────────────────────────────────────────────────────

    public int getBookedCount()  { return bookings.size(); }
    public int getAvailableSpaces() { return MAX_CAPACITY - bookings.size(); }
    public boolean hasSpace()    { return bookings.size() < MAX_CAPACITY; }

    // ── Package-private mutators (called by services) ─────────────────────────

    public void addBooking(Booking booking)  { bookings.add(booking); }
    public void removeBooking(Booking booking) { bookings.remove(booking); }
    public void addReview(Review review)     { reviews.add(review); }

    // ── Stats ─────────────────────────────────────────────────────────────────

    /**
     * Returns the average rating of all reviews for this lesson,
     * or 0.0 if there are no reviews.
     */
    public double getAverageRating() {
        if (reviews.isEmpty()) return 0.0;
        return reviews.stream()
                .mapToInt(Review::getRating)
                .average()
                .orElse(0.0);
    }

    /**
     * Total income generated by this lesson (price × number of bookings).
     */
    public double getTotalIncome() {
        return exercise.getPrice() * bookings.size();
    }

    @Override
    public String toString() {
        return String.format("[W%d] %s – %s %s (£%.2f) [%d/%d spaces]",
                weekendNumber, exercise.getDisplayName(),
                day.getDisplayName(), timeSlot.getDisplayName(),
                exercise.getPrice(), bookings.size(), MAX_CAPACITY);
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Lesson)) return false;
        return lessonId.equals(((Lesson) o).lessonId);
    }

    @Override
    public int hashCode() { return lessonId.hashCode(); }
}
